"""FastAPI Application Entrypoint for Gaming Intelligence Platform."""

import os
import json
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import redis

app = FastAPI(
    title="Gaming Intelligence Platform API",
    description="Real-Time Competitive Gaming Analytics, Cheat Detection, and Server Health Monitoring",
    version="1.0.0"
)

# Enable CORS for dashboard development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))


def get_redis_client():
    return redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=0, decode_responses=True)


@app.get("/")
async def root():
    return {
        "status": "online",
        "service": "gaming-intelligence-api",
        "timestamp": datetime.now(timezone.utc).isoformat()
    }


@app.get("/health")
async def health_check():
    redis_status = "unavailable"
    try:
        r = get_redis_client()
        if r.ping():
            redis_status = "connected"
    except Exception:
        redis_status = "disconnected"

    return {
        "status": "healthy" if redis_status == "connected" else "degraded",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "components": {
            "api": "ready",
            "redis": redis_status,
            "kafka": "configured"
        }
    }


@app.get("/api/v1/servers")
async def list_servers():
    """Returns real-time health metrics for all active game servers."""
    try:
        r = get_redis_client()
        server_ids = r.smembers("servers:active")
        results = []
        for s_id in server_ids:
            data = r.hgetall(f"server:{s_id}")
            if data:
                results.append(data)
        return {"servers": sorted(results, key=lambda x: x.get("server_id", ""))}
    except Exception as e:
        return {"servers": [], "error": str(e)}


@app.get("/api/v1/players/flagged")
async def list_flagged_players():
    """Returns players flagged by real-time cheat detection."""
    try:
        r = get_redis_client()
        player_ids = r.smembers("players:flagged")
        results = []
        for p_id in player_ids:
            data = r.hgetall(f"player:{p_id}")
            if data:
                results.append(data)
        return {"flagged_players": results}
    except Exception as e:
        return {"flagged_players": [], "error": str(e)}


@app.get("/api/v1/alerts/recent")
async def list_recent_alerts(limit: int = 20):
    """Returns recent alerts generated by streaming analytics."""
    limit = max(1, min(limit, 100))  # clamp: limit<=0 would make lrange return the whole list
    try:
        r = get_redis_client()
        raw_alerts = r.lrange("alerts:recent", 0, limit - 1)
        alerts = [json.loads(a) for a in raw_alerts]
        return {"alerts": alerts}
    except Exception as e:
        return {"alerts": [], "error": str(e)}
